name: Release
on:
  push:
jobs:
  release:
    name: Release on GitHub and PGXN
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Release on PGXN
        uses: pgxn/release-action@v0
        id: pgxn
        with:
          username: ${{ secrets.PGXN_USERNAME }}
          password: ${{ secrets.PGXN_PASSWORD }}
          dry-run: ${{ !startsWith( github.ref, 'refs/tags/v' ) }}
      - name: Generate Release Changes
        run: make latest-changes.md
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith( github.ref, 'refs/tags/v' )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "Release ${{ github.ref_name }}"
          body_path: latest-changes.md
          files: ${{ steps.pgxn.outputs.archive }}
